# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

#trigger:
#- main

pool:
  vmImage: 'windows-latest'

steps:
# - task: DownloadSecureFile@1
#   inputs:
#     secureFile: 'bznoctmdemos.cer'
# - task: CmdLine@2
#   inputs:
#     script: |
#       echo Importando certificado do OC
#       certutil -addstore -enterprise -f -v root $(DownloadSecureFile.SecureFilePath)
- task: UiPathTest@2
  inputs:
    testTarget: 'TestProject'
    orchestratorConnection: 'azDevOps'
    folderName: 'Shared'
- task: UiPathPack@2
  inputs:
    versionType: 'CurrentVersion'
    projectJsonPath: '$(Build.SourcesDirectory)'
    orchestratorConnection: 'azDevOps'
    outputPath: '$(Build.ArtifactStagingDirectory)\Output'
- task: UiPathDeploy@2
  inputs:
    orchestratorConnection: 'azDevOps'
    packagesPath: '$(Build.ArtifactStagingDirectory)\Output'
    folderName: 'Shared'
    entryPoints: 'Main.xaml'

