# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
#  vmImage: ubuntu-latest
  name: LAPTOP-JTORFD59

steps:
# - task: DownloadSecureFile@1
#   inputs:
#     secureFile: 'bznoctmdemos.cer'
# - task: CmdLine@2
#   inputs:
#     script: |
#       echo Importando certificado do OC
#       certutil -addstore -enterprise -f -v root $(DownloadSecureFile.SecureFilePath)

- task: PowerShell@2
  displayName: 'Workflow Analyzer'
  inputs:
    filePath: '$(Build.SourcesDirectory)\Data\Workflow-Analyzer-CLI-Script.ps1'
    arguments: '-ProjectFilePath $(Build.SourcesDirectory)\project.json -OutputFilePath $(Build.SourcesDirectory)\Data\Output'
    workingDirectory: '$(Build.SourcesDirectory)'

# - task: UiPathTest@2
#   displayName: 'Testing'
#   inputs:
#     testTarget: 'TestProject'
#     orchestratorConnection: 'azDevOps'
#     folderName: 'Shared'

# - task: UiPathPack@2
#   displayName: 'Packing'
#   inputs:
#     versionType: 'AutoVersion'
#     projectJsonPath: '$(Build.SourcesDirectory)'
#     orchestratorConnection: 'azDevOps'
#     outputPath: '$(Build.ArtifactStagingDirectory)\Output'

# - task: UiPathDeploy@2
#   displayName: 'Deployment'
#   inputs:
#     orchestratorConnection: 'azDevOps'
#     packagesPath: '$(Build.ArtifactStagingDirectory)\Output'
#     folderName: 'Shared'
#     entryPoints: 'Main.xaml'

- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'UiPath-LATAM-DEMO-TS_AzureDevOps'
    repositoryName: 'UiPath-LATAM/DEMO-TS_AzureDevOps'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'gitTag'
    title: 'AzureDevOps'
    releaseNotesSource: 'inline'
    releaseNotesInline: 'Azure DevOps Test'
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'